version: '3.4'
services:
  mariadb:
    image: mysql:8.0 # mariadb:11.5.2
    ports:
      - "13306:3306"
    command:
      --init-file /data/application/db.sql
    environment:
      MYSQL_ROOT_USER: javafxTest
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: javafxTest
      MYSQL_USER: javafxTest
      MYSQL_PASSWORD: changeme
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
      - ./db.sql:/data/application/db.sql

    # network_mode: "host"